import = ["~/.config/alacritty/base16-material.toml"]

[env]
TERM = "xterm-256color"

[window]
decorations = "full"
dimensions = { columns = 80, lines = 24 }
padding = { x = 2, y = 2 }

[font]
size = 10.0
normal = { family = "Hack Nerd Font Mono" }

[bell]
animation = "EaseOutExpo"
duration = 0

[selection]
semantic_escape_chars = ",│`|:\"' ()[]{}<>"

[mouse]
hide_when_typing = false
bindings = [
    { mouse = "Middle", action = "PasteSelection" }
]

[debug]
render_timer = false

[keyboard]
bindings = [
  { key = "V",        mods = "Control|Shift",    action = "Paste"                 },
  { key = "C",        mods = "Control|Shift",    action = "Copy"                  },
  { key = "V",        mods = "Command",          action = "Paste"                 },
  { key = "C",        mods = "Command",          action = "Copy"                  },
  { key = "Q",        mods = "Command",          action = "Quit"                  },
  { key = "W",        mods = "Command",          action = "Quit"                  },
  { key = "Insert",   mods = "Shift",            action = "PasteSelection"        },
  { key = "Home",                       chars = "\u001bOH",   mode = "AppCursor"  },
  { key = "Home",                       chars = "\u001b[1~",  mode = "~AppCursor" },
  { key = "End",                        chars = "\u001bOF",   mode = "AppCursor"  },
  { key = "End",                        chars = "\u001b[4~",  mode = "~AppCursor" },
  { key = "PageUp",   mods = "Shift",   chars = "\u001b[5;2~"                     },
  { key = "PageUp",   mods = "Control", chars = "\u001b[5;5~"                     },
  { key = "PageUp",                     chars = "\u001b[5~"                       },
  { key = "PageDown", mods = "Shift",   chars = "\u001b[6;2~"                     },
  { key = "PageDown", mods = "Control", chars = "\u001b[6;5~"                     },
  { key = "PageDown",                   chars = "\u001b[6~"                       },
  { key = "Left",     mods = "Shift",   chars = "\u001b[1;2D"                     },
  { key = "Left",     mods = "Control", chars = "\u001b[1;5D"                     },
  { key = "Left",     mods = "Alt",     chars = "\u001b[1;3D"                     },
  { key = "Left",                       chars = "\u001b[D",   mode = "~AppCursor" },
  { key = "Left",                       chars = "\u001bOD",   mode = "AppCursor"  },
  { key = "Right",    mods = "Shift",   chars = "\u001b[1;2C"                     },
  { key = "Right",    mods = "Control", chars = "\u001b[1;5C"                     },
  { key = "Right",    mods = "Alt",     chars = "\u001b[1;3C"                     },
  { key = "Right",                      chars = "\u001b[C",   mode = "~AppCursor" },
  { key = "Right",                      chars = "\u001bOC",   mode = "AppCursor"  },
  { key = "Up",       mods = "Shift",   chars = "\u001b[1;2A"                     },
  { key = "Up",       mods = "Control", chars = "\u001b[1;5A"                     },
  { key = "Up",       mods = "Alt",     chars = "\u001b[1;3A"                     },
  { key = "Up",                         chars = "\u001b[A",   mode = "~AppCursor" },
  { key = "Up",                         chars = "\u001bOA",   mode = "AppCursor"  },
  { key = "Down",     mods = "Shift",   chars = "\u001b[1;2B"                     },
  { key = "Down",     mods = "Control", chars = "\u001b[1;5B"                     },
  { key = "Down",     mods = "Alt",     chars = "\u001b[1;3B"                     },
  { key = "Down",                       chars = "\u001b[B",   mode = "~AppCursor" },
  { key = "Down",                       chars = "\u001bOB",   mode = "AppCursor"  },
  { key = "Tab",      mods = "Shift",   chars = "\u001b[Z"                        },
  { key = "F1",                         chars = "\u001bOP"                        },
  { key = "F2",                         chars = "\u001bOQ"                        },
  { key = "F3",                         chars = "\u001bOR"                        },
  { key = "F4",                         chars = "\u001bOS"                        },
  { key = "F5",                         chars = "\u001b[15~"                      },
  { key = "F6",                         chars = "\u001b[17~"                      },
  { key = "F7",                         chars = "\u001b[18~"                      },
  { key = "F8",                         chars = "\u001b[19~"                      },
  { key = "F9",                         chars = "\u001b[20~"                      },
  { key = "F10",                        chars = "\u001b[21~"                      },
  { key = "F11",                        chars = "\u001b[23~"                      },
  { key = "F12",                        chars = "\u001b[24~"                      },
  { key = "Back",                       chars = "\u007f"                          },
  { key = "Back",     mods = "Alt",     chars = "\u001b\u007f"                    },
  { key = "Insert",                     chars = "\u001b[2~"                       },
  { key = "Delete",                     chars = "\u001b[3~"                       },
]
