vim.keymap.set('c', 'вя', 'wq')
vim.keymap.set('c', 'в', 'w')
vim.keymap.set('c', 'я', 'q')

vim.keymap.set('', 'гх', 'gh')
vim.keymap.set('', 'гй', 'gj')
vim.keymap.set('', 'гк', 'gk')
vim.keymap.set('', 'гл', 'gl')

vim.keymap.set('', 'зг', 'zg')
vim.keymap.set('', 'зо', 'zo')
vim.keymap.set('', 'зЦ', 'zC')
vim.keymap.set('', 'зР', 'zR')
vim.keymap.set('', 'зМ', 'zM')

vim.keymap.set('', 'ч', '`')
vim.keymap.set('', 'я', 'q')
vim.keymap.set('', 'в', 'w')
vim.keymap.set('', 'е', 'e')
vim.keymap.set('', 'р', 'r')
vim.keymap.set('', 'т', 't')
vim.keymap.set('', 'ъ', 'y')
vim.keymap.set('', 'у', 'u')
vim.keymap.set('', 'и', 'i')
vim.keymap.set('', 'о', 'o')
vim.keymap.set('', 'п', 'p')
vim.keymap.set('', 'ш', '[')
vim.keymap.set('', 'щ', ']')

vim.keymap.set('', 'а', 'a')
vim.keymap.set('', 'с', 's')
vim.keymap.set('', 'д', 'd')
vim.keymap.set('', 'ф', 'f')
vim.keymap.set('', 'г', 'g')
vim.keymap.set('', 'х', 'h')
vim.keymap.set('', 'й', 'j')
vim.keymap.set('', 'к', 'k')
vim.keymap.set('', 'л', 'l')

vim.keymap.set('', 'з', 'z')
vim.keymap.set('', 'ь', 'x')
vim.keymap.set('', 'ц', 'c')
vim.keymap.set('', 'ж', 'v')
vim.keymap.set('', 'б', 'b')
vim.keymap.set('', 'н', 'n')
vim.keymap.set('', 'м', 'm')

vim.keymap.set('', 'Ч', '~')
vim.keymap.set('', 'Я', 'Q')
vim.keymap.set('', 'В', 'W')
vim.keymap.set('', 'Е', 'E')
vim.keymap.set('', 'Р', 'R')
vim.keymap.set('', 'Т', 'T')
vim.keymap.set('', 'Ъ', 'Y')
vim.keymap.set('', 'У', 'U')
vim.keymap.set('', 'И', 'I')
vim.keymap.set('', 'О', 'O')
vim.keymap.set('', 'П', 'P')
vim.keymap.set('', 'Ш', '{')
vim.keymap.set('', 'Щ', '}')

vim.keymap.set('', 'А', 'A')
vim.keymap.set('', 'С', 'S')
vim.keymap.set('', 'Д', 'D')
vim.keymap.set('', 'Ф', 'F')
vim.keymap.set('', 'Г', 'G')
vim.keymap.set('', 'Х', 'H')
vim.keymap.set('', 'Й', 'J')
vim.keymap.set('', 'К', 'K')
vim.keymap.set('', 'Л', 'L')

vim.keymap.set('', 'З', 'Z')
vim.keymap.set('', 'Ь', 'X')
vim.keymap.set('', 'Ц', 'C')
vim.keymap.set('', 'Ж', 'V')
vim.keymap.set('', 'Б', 'B')
vim.keymap.set('', 'Н', 'N')
vim.keymap.set('', 'М', 'M')
