vim.api.nvim_set_keymap('c', 'вя', 'wq', { noremap = true })
vim.api.nvim_set_keymap('c', 'в', 'w', { noremap = true })
vim.api.nvim_set_keymap('c', 'я', 'q', { noremap = true })

vim.api.nvim_set_keymap('', 'гх', 'gh', { noremap = true })
vim.api.nvim_set_keymap('', 'гй', 'gj', { noremap = true })
vim.api.nvim_set_keymap('', 'гк', 'gk', { noremap = true })
vim.api.nvim_set_keymap('', 'гл', 'gl', { noremap = true })

vim.api.nvim_set_keymap('', 'зг', 'zg', { noremap = true })
vim.api.nvim_set_keymap('', 'зо', 'zo', { noremap = true })
vim.api.nvim_set_keymap('', 'зЦ', 'zC', { noremap = true })
vim.api.nvim_set_keymap('', 'зР', 'zR', { noremap = true })
vim.api.nvim_set_keymap('', 'зМ', 'zM', { noremap = true })

vim.api.nvim_set_keymap('', 'ч', '`', { noremap = true })
vim.api.nvim_set_keymap('', 'я', 'q', { noremap = true })
vim.api.nvim_set_keymap('', 'в', 'w', { noremap = true })
vim.api.nvim_set_keymap('', 'е', 'e', { noremap = true })
vim.api.nvim_set_keymap('', 'р', 'r', { noremap = true })
vim.api.nvim_set_keymap('', 'т', 't', { noremap = true })
vim.api.nvim_set_keymap('', 'ъ', 'y', { noremap = true })
vim.api.nvim_set_keymap('', 'у', 'u', { noremap = true })
vim.api.nvim_set_keymap('', 'и', 'i', { noremap = true })
vim.api.nvim_set_keymap('', 'о', 'o', { noremap = true })
vim.api.nvim_set_keymap('', 'п', 'p', { noremap = true })
vim.api.nvim_set_keymap('', 'ш', '[', { noremap = true })
vim.api.nvim_set_keymap('', 'щ', ']', { noremap = true })

vim.api.nvim_set_keymap('', 'а', 'a', { noremap = true })
vim.api.nvim_set_keymap('', 'с', 's', { noremap = true })
vim.api.nvim_set_keymap('', 'д', 'd', { noremap = true })
vim.api.nvim_set_keymap('', 'ф', 'f', { noremap = true })
vim.api.nvim_set_keymap('', 'г', 'g', { noremap = true })
vim.api.nvim_set_keymap('', 'х', 'h', { noremap = true })
vim.api.nvim_set_keymap('', 'й', 'j', { noremap = true })
vim.api.nvim_set_keymap('', 'к', 'k', { noremap = true })
vim.api.nvim_set_keymap('', 'л', 'l', { noremap = true })

vim.api.nvim_set_keymap('', 'з', 'z', { noremap = true })
vim.api.nvim_set_keymap('', 'ь', 'x', { noremap = true })
vim.api.nvim_set_keymap('', 'ц', 'c', { noremap = true })
vim.api.nvim_set_keymap('', 'ж', 'v', { noremap = true })
vim.api.nvim_set_keymap('', 'б', 'b', { noremap = true })
vim.api.nvim_set_keymap('', 'н', 'n', { noremap = true })
vim.api.nvim_set_keymap('', 'м', 'm', { noremap = true })

vim.api.nvim_set_keymap('', 'Ч', '~', { noremap = true })
vim.api.nvim_set_keymap('', 'Я', 'Q', { noremap = true })
vim.api.nvim_set_keymap('', 'В', 'W', { noremap = true })
vim.api.nvim_set_keymap('', 'Е', 'E', { noremap = true })
vim.api.nvim_set_keymap('', 'Р', 'R', { noremap = true })
vim.api.nvim_set_keymap('', 'Т', 'T', { noremap = true })
vim.api.nvim_set_keymap('', 'Ъ', 'Y', { noremap = true })
vim.api.nvim_set_keymap('', 'У', 'U', { noremap = true })
vim.api.nvim_set_keymap('', 'И', 'I', { noremap = true })
vim.api.nvim_set_keymap('', 'О', 'O', { noremap = true })
vim.api.nvim_set_keymap('', 'П', 'P', { noremap = true })
vim.api.nvim_set_keymap('', 'Ш', '{', { noremap = true })
vim.api.nvim_set_keymap('', 'Щ', '}', { noremap = true })

vim.api.nvim_set_keymap('', 'А', 'A', { noremap = true })
vim.api.nvim_set_keymap('', 'С', 'S', { noremap = true })
vim.api.nvim_set_keymap('', 'Д', 'D', { noremap = true })
vim.api.nvim_set_keymap('', 'Ф', 'F', { noremap = true })
vim.api.nvim_set_keymap('', 'Г', 'G', { noremap = true })
vim.api.nvim_set_keymap('', 'Х', 'H', { noremap = true })
vim.api.nvim_set_keymap('', 'Й', 'J', { noremap = true })
vim.api.nvim_set_keymap('', 'К', 'K', { noremap = true })
vim.api.nvim_set_keymap('', 'Л', 'L', { noremap = true })

vim.api.nvim_set_keymap('', 'З', 'Z', { noremap = true })
vim.api.nvim_set_keymap('', 'Ь', 'X', { noremap = true })
vim.api.nvim_set_keymap('', 'Ц', 'C', { noremap = true })
vim.api.nvim_set_keymap('', 'Ж', 'V', { noremap = true })
vim.api.nvim_set_keymap('', 'Б', 'B', { noremap = true })
vim.api.nvim_set_keymap('', 'Н', 'N', { noremap = true })
vim.api.nvim_set_keymap('', 'М', 'M', { noremap = true })
